import {initializeApp}from'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,collection,doc,getDoc,setDoc,deleteDoc,addDoc,updateDoc,serverTimestamp,query,where,orderBy,onSnapshot}from'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyApXaG_rT0-veZzozy3Wtns2IGHZqDOYXc',authDomain:'bss-astronomy-2026.firebaseapp.com',projectId:'bss-astronomy-2026',storageBucket:'bss-astronomy-2026.firebasestorage.app',messagingSenderId:'1054853511225',appId:'1:1054853511225:web:c95e38bac3512d815b75e8'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),teacherEmail='sjm4104@gmail.com';
const projects=window.PROJECTS||[],topics=[...new Set(projects.map(p=>p.topic))];let selected='전체',queryText='',currentUser=null,activeProject=null,stopFeedback=null;
const cards=document.querySelector('#cards'),count=document.querySelector('#count'),modal=document.querySelector('#modal'),authBtn=document.querySelector('#authBtn');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const isTeacher=()=>currentUser?.email===teacherEmail;
function render(){let arr=projects.filter(p=>(selected==='전체'||p.topic===selected)&&(`${p.title} ${p.studentId} ${p.topic}`).toLowerCase().includes(queryText.toLowerCase()));let sort=document.querySelector('#sort').value;arr.sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'ko'):sort==='topic'?a.topic.localeCompare(b.topic,'ko'):a.id.localeCompare(b.id));cards.innerHTML=arr.map(p=>`<article class="card" style="--accent:${p.accent}" data-id="${p.id}"><span class="project-num">STUDENT ${p.studentId}</span><span class="tag">${p.topic}</span><h3>${p.title}</h3><span class="student">학번 ${p.studentId}</span><span class="open">VIEW PROJECT →</span></article>`).join('');count.textContent=`${arr.length}개 프로젝트`;document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openProject(c.dataset.id))}
const filter=document.querySelector('#topicFilters');['전체',...topics].forEach(t=>{let b=document.createElement('button');b.textContent=t;b.className=t==='전체'?'active':'';b.onclick=()=>{selected=t;filter.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()};filter.append(b)});document.querySelector('#search').oninput=e=>{queryText=e.target.value;render()};document.querySelector('#sort').onchange=render;
async function login(){try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){alert('로그인에 실패했습니다. Firebase Authentication의 Google 설정과 Authorized domain을 확인해 주세요.')}}
async function toggleLike(){if(!currentUser)return login();let ref=doc(db,'projects',activeProject.id,'likes',currentUser.uid),snap=await getDoc(ref);if(snap.exists())await deleteDoc(ref);else await setDoc(ref,{projectId:activeProject.id,userId:currentUser.uid,createdAt:serverTimestamp()});updateLikeButton()}
async function updateLikeButton(){let b=document.querySelector('#likeBtn');if(!b||!activeProject)return;b.textContent='♡ 좋아요';if(currentUser&&(await getDoc(doc(db,'projects',activeProject.id,'likes',currentUser.uid))).exists())b.textContent='♥ 좋아요 취소'}
function listenFeedback(){stopFeedback?.();let q=isTeacher()?query(collection(db,'feedback'),where('projectId','==',activeProject.id),orderBy('createdAt','desc')):query(collection(db,'feedback'),where('projectId','==',activeProject.id),where('status','==','published'),orderBy('createdAt','desc'));stopFeedback=onSnapshot(q,snap=>{let list=document.querySelector('#feedbackList');if(!list)return;list.innerHTML=snap.empty?'<p class="empty-feedback">아직 공개된 글이 없습니다. 첫 번째 응원을 남겨 보세요.</p>':snap.docs.map(d=>{let x=d.data(),pending=x.status==='pending';return `<article class="feedback ${pending?'pending':''}"><span>${x.type==='question'?'질문':'방명록'}${pending?' · 검토 대기':''}</span><p>${esc(x.content)}</p><small>${esc(x.authorName||'방문자')}</small>${isTeacher()?`<div class="moderate"><button data-publish="${d.id}">공개</button><button data-hide="${d.id}">숨김</button></div>`:''}</article>`}).join('');list.querySelectorAll('[data-publish]').forEach(b=>b.onclick=()=>moderate(b.dataset.publish,'published'));list.querySelectorAll('[data-hide]').forEach(b=>b.onclick=()=>moderate(b.dataset.hide,'hidden'))},err=>console.warn(err.message))}
async function moderate(id,status){await updateDoc(doc(db,'feedback',id),{status,moderatedAt:serverTimestamp()})}
async function submitFeedback(e){e.preventDefault();if(!currentUser)return login();let f=new FormData(e.target),content=String(f.get('content')).trim();if(!content)return;try{await addDoc(collection(db,'feedback'),{projectId:activeProject.id,type:f.get('type'),content,status:'pending',authorUid:currentUser.uid,authorName:currentUser.displayName||'방문자',createdAt:serverTimestamp()});e.target.reset();alert('글을 받았습니다. 교사 검토 후 공개됩니다.')}catch(e){alert('저장하지 못했습니다. 로그인과 보안 규칙을 확인해 주세요.')}}
function openProject(id){activeProject=projects.find(x=>x.id===id);let p=activeProject;document.querySelector('#modalBody').innerHTML=`<div class="modal-top"><span class="tag" style="--accent:${p.accent}">${p.topic}</span><h2>${p.title}</h2><p>2026학년도 2학년 고급지구과학 · 학번 ${p.studentId}</p>${p.file?`<a class="launch" href="${p.file}" target="_blank">시뮬레이션 실행 ↗</a>`:''}</div><div class="modal-grid"><section><h4>개발 동기 및 목적</h4><p>${p.purpose}</p></section><section><h4>과학적 원리 및 수식</h4><p>${p.principle}</p></section><section><h4>시뮬레이션 사용 방법</h4><p>${p.how}</p></section><section><h4>과학적 한계점</h4><p>${p.limit}</p></section></div><section class="community"><div class="community-head"><div><h3>작품 피드백</h3><p>질문과 응원이 다음 개선의 출발점이 됩니다.</p></div><button id="likeBtn" class="like">♡ 좋아요</button></div>${currentUser?'':'<p class="login-note">질문·방명록·좋아요는 Google 로그인 후 이용할 수 있습니다.</p>'}<form id="feedbackForm"><select name="type"><option value="question">질문</option><option value="guestbook">방명록</option></select><textarea name="content" maxlength="1000" placeholder="작품에 관한 질문이나 응원을 남겨 주세요."></textarea><button type="submit">검토 요청 보내기</button></form><div id="feedbackList"></div></section>`;modal.showModal();document.querySelector('#likeBtn').onclick=toggleLike;document.querySelector('#feedbackForm').onsubmit=submitFeedback;updateLikeButton();listenFeedback()}
authBtn.onclick=()=>currentUser?signOut(auth):login();onAuthStateChanged(auth,user=>{currentUser=user;authBtn.textContent=user?`${user.displayName||'로그인됨'} · 로그아웃`:'Google 로그인';if(activeProject&&modal.open)openProject(activeProject.id)});document.querySelector('#closeBtn').onclick=()=>{stopFeedback?.();modal.close()};modal.onclick=e=>{if(e.target===modal){stopFeedback?.();modal.close()}};document.querySelector('#randomBtn').onclick=()=>{if(projects.length)openProject(projects[Math.floor(Math.random()*projects.length)].id)};document.querySelector('#guideBtn').onclick=()=>alert('2026학년도 2학년 고급지구과학 수업에서 제작한 천문학 시뮬레이션 아카이브입니다.\n지도교사: 신진몽\n\n질문과 방명록은 교사 검토 후 공개됩니다.');render();
