import{initializeApp}from'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import{getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged,signInAnonymously}from'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import{getFirestore,collection,doc,getDoc,getDocs,setDoc,deleteDoc,addDoc,updateDoc,serverTimestamp,query,where,onSnapshot}from'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const cfg={apiKey:'AIzaSyApXaG_rT0-veZzozy3Wtns2IGHZqDOYXc',authDomain:'bss-astronomy-2026.firebaseapp.com',projectId:'bss-astronomy-2026',storageBucket:'bss-astronomy-2026.firebasestorage.app',messagingSenderId:'1054853511225',appId:'1:1054853511225:web:c95e38bac3512d815b75e8'};
const app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),teacherEmail='sjm4104@gmail.com';
const projects=window.PROJECTS||[],topics=[...new Set(projects.map(p=>p.topic))];let selected='전체',queryText='',user=null,active=null,stopFeedback,stopLikes,stopSiteFeedback;
const $=s=>document.querySelector(s),cards=$('#cards'),count=$('#count'),modal=$('#modal'),guestDialog=$('#guestbookDialog'),authBtn=$('#authBtn');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const teacher=()=>user?.email===teacherEmail;const signedGoogle=()=>user&&!user.isAnonymous;
function stamp(v){return v?.seconds?new Date(v.seconds*1000).toLocaleDateString('ko-KR'):''}function sortDocs(a){return a.sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0))}
function render(){let a=projects.filter(p=>(selected==='전체'||p.topic===selected)&&(`${p.title} ${p.studentId} ${p.topic}`).toLowerCase().includes(queryText.toLowerCase()));let sort=$('#sort').value;a.sort((x,y)=>sort==='title'?x.title.localeCompare(y.title,'ko'):sort==='topic'?x.topic.localeCompare(y.topic,'ko'):x.id.localeCompare(y.id));cards.innerHTML=a.map(p=>`<article class="card" style="--accent:${p.accent}" data-id="${p.id}"><span class="project-num">STUDENT ${p.studentId}</span><span class="tag">${p.topic}</span><h3>${p.title}</h3><span class="student">학번 ${p.studentId}</span><span class="open">VIEW PROJECT →</span></article>`).join('');count.textContent=`${a.length}개 프로젝트`;document.querySelectorAll('.card').forEach(x=>x.onclick=()=>openProject(x.dataset.id))}
const filters=$('#topicFilters');['전체',...topics].forEach(t=>{let b=document.createElement('button');b.textContent=t;b.className=t==='전체'?'active':'';b.onclick=()=>{selected=t;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()};filters.append(b)});$('#search').oninput=e=>{queryText=e.target.value;render()};$('#sort').onchange=render;
const question=p=>{let q={
 '태양계 · 궤도':'궤도 반지름이나 초기 속도를 바꾸면 공전 주기와 궤도 모양은 어떻게 달라질까요?',
 '항성 · 진화':'질량이 다른 별은 왜 서로 다른 색·밝기·수명을 갖게 될까요?',
 '은하 · 우주론':'관측값이 현재의 모형과 다르다면, 어떤 보이지 않는 변인을 의심할 수 있을까요?',
 '달 · 식 현상':'관찰자의 위치와 궤도 기울기를 바꾸면 어떤 조건에서 현상이 사라질까요?',
 '빛 · 관측':'관측자가 실제로 얻는 정보와 천체의 본래 물리량은 어떻게 다를까요?',
 '중력 · 운동':'이 모형에서 무시한 힘을 하나 추가한다면 결과는 어떻게 달라질까요?'};return q[p.topic]||'한 가지 변인을 바꾸었을 때 무엇이 달라지는지 예측한 뒤 직접 확인해 보세요.'};
async function googleLogin(){try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){alert('Google 로그인에 실패했습니다. Firebase Authentication 설정을 확인해 주세요.')}}
function accountNeeded(){if(signedGoogle())return true;alert('방명록과 질문은 Google 로그인 후 작성할 수 있습니다.');googleLogin();return false}
async function like(){if(!user)return;let ref=doc(db,'projects',active.id,'likes',user.uid),snap=await getDoc(ref);if(snap.exists())await deleteDoc(ref);else await setDoc(ref,{projectId:active.id,userId:user.uid,createdAt:serverTimestamp()})}
function listenLikes(){stopLikes?.();stopLikes=onSnapshot(collection(db,'projects',active.id,'likes'),s=>{let b=$('#likeBtn');if(!b)return;b.textContent=`♥ ${s.size}명이 응원했어요`;let mine=s.docs.some(x=>x.id===user?.uid);b.classList.toggle('liked',mine);b.title=mine?'다시 누르면 좋아요가 취소됩니다.':'좋아요를 남기세요.'})}
function card(x,admin=false){let wait=x.status==='pending';return `<article class="feedback ${wait?'pending':''}"><span>${x.type==='question'?'질문':x.type==='guestbook'?'방명록':x.type==='impression'?'전체 감상':x.type==='suggestion'?'개선 제안':'전체 질문'}${wait?' · 검토 대기':''}</span><p>${esc(x.content)}</p><small>${esc(x.authorName||'방문자')} · ${stamp(x.createdAt)}</small>${admin?`<div class="moderate"><button data-pub="${x.id}">공개</button><button data-hide="${x.id}">숨김</button></div>`:''}</article>`}
function bindModerate(root,col){root.querySelectorAll('[data-pub]').forEach(b=>b.onclick=()=>updateDoc(doc(db,col,b.dataset.pub),{status:'published',moderatedAt:serverTimestamp()}));root.querySelectorAll('[data-hide]').forEach(b=>b.onclick=()=>updateDoc(doc(db,col,b.dataset.hide),{status:'hidden',moderatedAt:serverTimestamp()}))}
function listenProjectFeedback(){stopFeedback?.();let q=teacher()?query(collection(db,'feedback'),where('projectId','==',active.id)):query(collection(db,'feedback'),where('projectId','==',active.id),where('status','==','published'));stopFeedback=onSnapshot(q,s=>{let list=$('#feedbackList');if(!list)return;let a=sortDocs(s.docs.map(d=>({...d.data(),id:d.id})));list.innerHTML=a.length?a.map(x=>card(x,teacher())).join(''):'<p class="empty-feedback">아직 공개된 글이 없습니다. 첫 번째 응원을 남겨 보세요.</p>';bindModerate(list,'feedback')})}
async function submitProject(e){e.preventDefault();if(!accountNeeded())return;let f=new FormData(e.target),content=String(f.get('content')).trim();if(!content)return;await addDoc(collection(db,'feedback'),{projectId:active.id,type:f.get('type'),content,status:'pending',authorUid:user.uid,authorName:user.displayName||'방문자',createdAt:serverTimestamp()});e.target.reset();alert('글을 받았습니다. 교사 검토 후 공개됩니다.')}
function openProject(id){active=projects.find(x=>x.id===id);let p=active;$('#modalBody').innerHTML=`<div class="modal-top"><span class="tag" style="--accent:${p.accent}">${p.topic}</span><h2>${p.title}</h2><p>2026학년도 2학년 고급지구과학 · 학번 ${p.studentId}</p>${p.file?`<a class="launch" href="${p.file}" target="_blank">시뮬레이션 실행 ↗</a>`:''}</div><div class="modal-grid"><section><h4>개발 동기 및 목적</h4><p>${p.purpose}</p></section><section><h4>과학적 원리 및 수식</h4><p>${p.principle}</p></section><section><h4>시뮬레이션 사용 방법</h4><p>${p.how}</p></section><section><h4>과학적 한계점</h4><p>${p.limit}</p></section><aside class="inquiry"><h4>탐구 질문 카드</h4><p>${question(p)}</p></aside></div><section class="community"><div class="community-head"><div><h3>작품 피드백</h3><p>질문과 응원이 다음 개선의 출발점이 됩니다.</p></div><button id="likeBtn" class="like">♥ 좋아요</button></div>${signedGoogle()?'':'<p class="login-note">좋아요는 로그인 없이 가능하며, 질문·방명록은 Google 로그인 후 이용할 수 있습니다.</p>'}<form id="projectForm"><select name="type"><option value="question">질문</option><option value="guestbook">방명록</option></select><textarea name="content" maxlength="1000" placeholder="작품에 관한 질문이나 응원을 남겨 주세요."></textarea><button type="submit">검토 요청 보내기</button></form><div id="feedbackList"></div></section>`;modal.showModal();$('#likeBtn').onclick=like;$('#projectForm').onsubmit=submitProject;listenLikes();listenProjectFeedback()}
function openGuestbook(){guestDialog.showModal();$('#guestbookBody').innerHTML=`<section class="guestbook-wrap"><h2>전체 방명록</h2><p class="lead">부산과학고 고급지구과학 천문학 시뮬레이션 전시에 대한 감상과 제안을 남겨 주세요.</p><form id="siteForm"><select name="type"><option value="impression">전체 감상</option><option value="suggestion">개선 제안</option><option value="question">전체 질문</option></select><textarea name="content" maxlength="1000" placeholder="수업과 전시에 관한 의견을 남겨 주세요."></textarea><button>검토 요청 보내기</button></form><div id="siteFeedbackList"></div></section>`;$('#siteForm').onsubmit=submitSite;listenSiteFeedback()}
function listenSiteFeedback(){stopSiteFeedback?.();let q=teacher()?collection(db,'siteFeedback'):query(collection(db,'siteFeedback'),where('status','==','published'));stopSiteFeedback=onSnapshot(q,s=>{let list=$('#siteFeedbackList');if(!list)return;let a=sortDocs(s.docs.map(d=>({...d.data(),id:d.id})));list.innerHTML=a.length?a.map(x=>card(x,teacher())).join(''):'<p class="empty-feedback">아직 공개된 글이 없습니다.</p>';bindModerate(list,'siteFeedback')})}
async function submitSite(e){e.preventDefault();if(!accountNeeded())return;let f=new FormData(e.target),content=String(f.get('content')).trim();if(!content)return;await addDoc(collection(db,'siteFeedback'),{type:f.get('type'),content,status:'pending',authorUid:user.uid,authorName:user.displayName||'방문자',createdAt:serverTimestamp()});e.target.reset();alert('글을 받았습니다. 교사 검토 후 공개됩니다.')}
authBtn.onclick=()=>signedGoogle()?signOut(auth):googleLogin();onAuthStateChanged(auth,u=>{if(!u){signInAnonymously(auth).catch(()=>{});return}user=u;authBtn.textContent=signedGoogle()?`${u.displayName||'로그인됨'} · 로그아웃`:'Google 로그인';$('#adminLink').hidden=!teacher();if(active&&modal.open)openProject(active.id);if(guestDialog.open)openGuestbook()});
$('#closeBtn').onclick=()=>{stopFeedback?.();stopLikes?.();modal.close()};$('#guestbookCloseBtn').onclick=()=>{stopSiteFeedback?.();guestDialog.close()};modal.onclick=e=>{if(e.target===modal)$('#closeBtn').click()};guestDialog.onclick=e=>{if(e.target===guestDialog)$('#guestbookCloseBtn').click()};$('#siteGuestbookBtn').onclick=openGuestbook;$('#randomBtn').onclick=()=>openProject(projects[Math.floor(Math.random()*projects.length)].id);$('#guideBtn').onclick=()=>alert('2026학년도 2학년 고급지구과학 수업에서 제작한 천문학 시뮬레이션 아카이브입니다.\n지도교사: 신진몽\n\n질문과 방명록은 교사 검토 후 공개됩니다.');render();
